name: FreeBSD

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-12
    name: FreeBSD build

    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Get KincTools_freebsd_x64
      run: git clone https://github.com/Kode/KincTools_freebsd_x64.git
    - name: Compile in FreeBSD VM
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
      id: build
      uses: vmactions/freebsd-vm@v0
      with:
        release: 13.1
        envs: 'ROBBOT_PASS GITHUB_SHA'
        usesh: false
        sync: rsync
        copyback: false
        mem: 10240
        prepare: pkg install -y alsa-lib libXinerama mesa-libs libXi bash git ninja
        run: |
          bash -c './KincTools_freebsd_x64/kmake --compile --compiler clang'
          # Copy binary
          cp build/Release/krafix KincTools_freebsd_x64/krafix
          # Git config
          git config --global --add safe.directory /Users/runner/work/krafix/krafix/KincTools_freebsd_x64
          git config --global user.name "Robbot"
          git config --global user.email "robbot2019@robdangero.us"
          # Commit binary
          git -C KincTools_freebsd_x64 commit -a -m "Update krafix binary to $GITHUB_SHA." && set _commit=0 || set _commit=1
          # Tag binary
          if ( $_commit == 0 ) git -C KincTools_freebsd_x64 tag kmake_$GITHUB_SHA
          # Push binary
          git -C KincTools_freebsd_x64 push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/KincTools_freebsd_x64.git main --tags && set _push1=0 || set _push1=1
          # Pull
          if ( $_commit == 0 && $_push1 == 1 ) git -C KincTools_freebsd_x64 pull --no-rebase
          # Push again
          if ( $_commit == 0 && $_push1 == 1 ) git -C KincTools_freebsd_x64 push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/KincTools_freebsd_x64.git main --tags || true
